language: node_js
node_js:
- '0.12'
- '0.10'
sudo: false
deploy:
  provider: npm
  email: npm@thomwright.co.uk
  api_key:
    secure: oG2FAoj2ZmEZuGwfvkD/aIJaPGTkUZ2ZFVPBE/JXWyFBn5y+0wh7AV5oKTSJbX2f/J4zuHyBVSoCYVPD1DR1wGz1TPMVetaQpMV3dFV9sg0+mEQqN1+nHwLKkXO1VCLtKJalQptbCEF/H1gIHBRq3HYGmfJY5YQIddlvY/pVBn1r9HglX4vszBHaAVeymTxflnxsx+J5Mvb3APNgXRvG9/zYSHWR2z6M2RA+jq17xKLFE+GnLiQ++u87EIrLysgunZwqIoHgLO2ILp17gsXtg5Y9YLwgHWbKF67tZBwADdmQm1iz1Cd1Go5WEPAXY7Fdf1GDHcFxcZjh/4WRHqc0hmYUvNU8mVFFEgdNOwhAJypDIPCmxSsPFKqL+n8/jpCxdUBoPZr3GbYF+C2iuMGMnQA5Io/ObIbeJ67JtunjUbTJT4ZfggpFa+1efNQf38XFisgJczXn2Lz8FutFvO/DPaMY07oRjYag827Uk/9SNYleQ7HSpqX7DbsROgTNeSLSmWYWj/kuKDzL7CXzcfMXfO3m0BKh/EK7syaq46umFbygo32/2FAfT5FWqzGAqP+UW0nbxJqJ8GAtByDdUTPv031bJnRaQjseJJQSvpQ/z9QPxVki0hFe2gS4RMgeJYVmYh4uamqHJoe/AeylBAy00nUsH0lku03yl1hP/oxYJGc=
  on:
    tags: true
    repo: ThomWright/flyd-timeInterval
notifications:
  email:
    on_success: never
    on_failure: always
